### ISSUE TITLE
A simple roadmap for solving HJBE and optimal stopping problems

### ISSUE THREAD

**Issue by jlperla** [SciML/DiffEqOperators.jl#45]
@ChrisRackauckas @FernandoKuwer
More later, but this should give a sense of where we will eventually want to go, adding on pieces to test each time.  First, solve everything in the **stationary** setup (i.e. only a singleton in the time dimension, which leads to an ODE).
- [ ] stationary, univariate diffusion with reflecting barriers, a uniform grid, and a constant discount rate.  Posted as #44
- [ ] add in absorbing barriers instead of reflecting barriers (especially an absorbing at the bottom and a reflecting at the top).  Roughly shown in (10) and (11) of [Finite Differences](https://github.com/econtoolkit/continuous_time_methods/blob/master/operator_discretization_finite_differences.pdf)
- [ ] add in a jump-diffusion process with a jump size as a function of the current state.  The reflecting barriers there are tricky.
- [ ] add in support for non-uniform grids.  Discussed in detail in [Finite Differences](https://github.com/econtoolkit/continuous_time_methods/blob/master/operator_discretization_finite_differences.pdf)

In all cases, the easiest test is to look at the generated discretized matrix and to solve a simple HJBE, as discussed in (54) to (56) of [Finite Differences](https://github.com/econtoolkit/continuous_time_methods/blob/master/operator_discretization_finite_differences.pdf)

While this is the most important set of features for our immediate project, there are plenty of other useful features.  First, look at the **time varying** versions, which generate a PDE:
- [ ] Add in time-variation in all parameters/functions of the univariate jump-diffusion process (including boundaries).  The assumption is that the final step the parameters have converged (and hence it is at the stationary level).  See Section 2 of [Finite Differences](https://github.com/econtoolkit/continuous_time_methods/blob/master/operator_discretization_finite_differences.pdf)
- [ ] Add in time-varying discount rates

Next, expand the set of stochastic processes
- [ ] Add in an additional discretely-valued state variable which evolves according to a continuous-time markov chain.
- [ ] Add in 2 dimensional diffusion processes.  Need to be careful with the upwind process there, since monotonicity is subtle.
